# Generated by Django 3.1.3 on 2020-12-11 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Testmania', '0007_auto_20201202_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='isEditorsChoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contests',
            name='contest',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
